src/Entity/Animal.php
<?php

namespace App\Entity;

use App\Repository\AnimalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: AnimalRepository::class)]
class Animal
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"la categorie ne doit pas etre vide")]
    private ?string $Categorie = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"le poid ne doit pas etre vide")]
    private ?float $Poid = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"le poid ne doit pas etre vide")]
    private ?string $etat = null;

    #[ORM\ManyToOne(inversedBy: 'animals')]
    private ?Reserve $reserve = null;

    #[ORM\Column(length: 255)]
    private ?string $imageLink = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\OneToMany(mappedBy: 'idanimal', targetEntity: Adopter::class)]
    private Collection $adopters;

    public function __construct()
    {
        $this->adopters = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategorie(): ?string
    {
        return $this->Categorie;
    }

    public function setCategorie(string $Categorie): static
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    public function getPoid(): ?float
    {
        return $this->Poid;
    }

    public function setPoid(float $Poid): static
    {
        $this->Poid = $Poid;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): static
    {
        $this->etat = $etat;

        return $this;
    }

    public function getReserve(): ?Reserve
    {
        return $this->reserve;
    }

    public function setReserve(?Reserve $reserve): static
    {
        $this->reserve = $reserve;

        return $this;
    }

    public function getImageLink(): ?string
    {
        return $this->imageLink;
    }

    public function setImageLink(string $imageLink): static
    {
        $this->imageLink = $imageLink;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection<int, Adopter>
     */
    public function getAdopters(): Collection
    {
        return $this->adopters;
    }

    public function addAdopter(Adopter $adopter): static
    {
        if (!$this->adopters->contains($adopter)) {
            $this->adopters->add($adopter);
            $adopter->setIdanimal($this);
        }

        return $this;
    }

    public function removeAdopter(Adopter $adopter): static
    {
        if ($this->adopters->removeElement($adopter)) {
            // set the owning side to null (unless already changed)
            if ($adopter->getIdanimal() === $this) {
                $adopter->setIdanimal(null);
            }
        }

        return $this;
    }



    public function __toString(): string
    {
        // Return a meaningful representation of the Animal entity,
        // for example, its name or some other descriptive property.
        return $this->getCategorie() ?? 'Animal';
    }
}

templates/dechet/addformdechet.html.twig
{{form(f)}}

templates/dechet/dechet.html.twig
<!DOCTYPE html>
<html>
    <head>
        <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
            <div class="container">
                <a class="navbar-brand text-uppercase fw-bold d-lg-none" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="index.html">Acceuil</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="about.html">à propos</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="jardin.html">Jardins</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{{ path('app_event')}}">Évènement</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="animaux.html">Animaux</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="/recyclage">Centre de recyclage</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="puits.html">Puits</a></li>
                        <li class="nav-item px-lg-6"><a class="nav-link text-uppercase" href="index.html">Se Connecter</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
       <link rel="icon" type="image/x-icon" href="{{ asset('assets/img/logo.png') }}" />

        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
  <link href="{{ asset( 'css/styles.css')}}" rel="stylesheet" />
    </head>
    <body>
        <header>
            <h1 class="site-heading text-center text-faded d-none d-lg-block">
                <span class="site-heading-upper text-primary mb-3">Protégeons la nature, préservons notre avenir</span>
                <span class="site-heading-lower">The Tree Well</span>
            </h1>
        </header>
        <!-- Navigation-->
        
        
        <div class="container">
                
            <div class="col-xl-9 mx-auto">
               
                {% block body %}
                
                <section class="page-section cta">
                    
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-inner bg-faded text-center rounded">
                    <h2 class="section-heading mb-4">
                        <h1>Liste des dechets</h1>
                                    <table border="3" class=centriq>
                                <thead>
                                    <tr>
                                        <th>Identifiant</th>
                                        
                            <th>Catégorie</th>
                            <td>Description</td>
                            <td>Date de récupération</td>
                            <th>Source du dechet</th>
                            <th>Etat du dechet</th>
                            <th>Identifiant du centre</th>
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for a in recyclage.dechets %}
                        <tr>
                        
                         <td>{{ a.id }}</td>
                         <td>{{ a.categrie }}</td>
                         <td>{{ a.description }}</td>
                         <td>{{ a.date|date('d-M-y') }}</td>
                         <td>{{ a.source }}</td>
                         <td>{{ a.etat }}</td>
                         <td>{{ a.idrecyclage }}</td>
                         <td>
                            <a href ="{{path('dechet_show',{'id':'recyclage.id'})}}"><button> Dechet à recycler </button></a>
                            </td>
                        </tr>
                        
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


                {% endblock %}

            </div>
       
    </div>
</section>
        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">Copyright &copy; The Tree Well 2024</p></div>
        </footer>
            
        {% endblock %}

        {% block javascripts %}
 <!-- Bootstrap core JS-->
    <script src="{{ asset('https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js') }}"></script>

        <!-- Core theme JS-->
<script src="{{ asset('js/scripts.js') }}"></script>

        {% endblock %}
    </head>
  
</html>

templates/dechet/dechetback.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Gestion dechet</title>
        <link rel="icon" type="image/x-icon" href="{{ asset('assets_back/img/logo.png') }}" />
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link href="{{ asset('assets_back/css/styles.css') }}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="index.html">The Tree Well</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->            
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            
                            <div class="sb-sidenav-menu-heading">Interface</div>                             
                            
                            <a class="nav-link" href="user.html">
                                <div class="sb-nav-link-icon"></i></div>
                               user
                            </a>
                            <a class="nav-link" href="gestion_reserve_naturelle.html">
                                <div class="sb-nav-link-icon"></i></div>
                                Gestion reserve naturelle
                            </a>
                            <a class="nav-link" href="gestion_dechet.html">
                                <div class="sb-nav-link-icon"></i></div>
                                Gestion Dechet
                            </a>
                            <a class="nav-link" href="gestion_jardin.html">
                                <div class="sb-nav-link-icon"></i></div>
                                Gestion Jardin
                            </a>
                            <a class="nav-link" href="gestion_nappe_d_eau.html">
                                <div class="sb-nav-link-icon"></i></div>
                                Gestion Nappe D Eau
                            </a>
                            <a class="nav-link" href="gestion_evenement.html">
                                <div class="sb-nav-link-icon"></i></div>
                                Gestion evenement
                            </a>
                        </div>
                    </div>
                    
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                   
                    <div class="container">
                
                        <div class="col-xl-9 mx-auto">
                           
                            {% block body %}
                            
                            <section class="page-section cta">
                                
                <div class="container">
                    <div class="row">
                        <div class="col-xl-9 mx-auto">
                            <div class="cta-inner bg-faded text-center rounded">
                                <h2 class="section-heading mb-4">
                                    <h1>Liste des dechets</h1>
                                    <table border="3" class=centriq>
                                <thead>
                                    <tr>
                                        <th>Identifiant</th>
                                        
                            <th>Catégorie</th>
                            <td>Description</td>
                            <td>Date de récupération</td>
                            <th>Source du dechet</th>
                            <th>Etat du dechet</th>
                            <th>Identifiant du centre</th>
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for a in recyclage.dechets %}
                        <tr>
                        
                         <td>{{ a.id }}</td>
                         <td>{{ a.categrie }}</td>
                         <td>{{ a.description }}</td>
                         <td>{{ a.date|date('d-M-y') }}</td>
                         <td>{{ a.source }}</td>
                         <td>{{ a.etat }}</td>
                         <td>{{ a.idrecyclage }}</td>
                         <td>
                            <a href ="{{path('recyclage_update',{'id':'recyclage.id'})}}">Modifier</a> 
                            <a href ="{{path('recyclage_delete',{'id':'recyclage.id'})}}">Supprimer</a> 
                            <a href ="{{path('dechetback_show',{'id':'nappe.id'})}}"><button> Dechéts à recycler </button></a>             
                            </td>
                        </tr>
                                    
                                    {% endfor %}
                                    
                                </tbody>
                                
                            </table>
                            
                        </div>
                        <a href ="{{path('recyclage_add')}}"><button> Ajouter un centre de recyclage </button></a>
                    </div>
                    
                </div>
            </div>
            
    
                            {% endblock %}



                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2023</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
        <script src="js/datatables-simple-demo.js"></script>
    </body>
</html>